/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': 'var(--surface-variant)',
        'inverse-surface': 'var(--inverse-surface)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'surface-dim': 'var(--surface-dim)',
        'on-primary-container': 'var(--on-primary-container)',
        'primary-container': 'var(--primary-container)',
        'surface': 'var(--surface)',
        'error-container': 'var(--error-container)',
        'tertiary': 'var(--tertiary)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'primary-fixed': 'var(--primary-fixed)',
        'on-secondary': 'var(--on-secondary)',
        'outline': 'var(--outline)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-surface': 'var(--on-surface)',
        'on-error-container': 'var(--on-error-container)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'on-primary': 'var(--on-primary)',
        'primary': 'var(--primary)',
        'secondary': 'var(--secondary)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'error': 'var(--error)',
        'on-background': 'var(--on-background)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'surface-bright': 'var(--surface-bright)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'outline-variant': 'var(--outline-variant)',
        'secondary-container': 'var(--secondary-container)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'on-error': 'var(--on-error)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-tint': 'var(--surface-tint)',
        'on-tertiary': 'var(--on-tertiary)',
        'surface-container-high': 'var(--surface-container-high)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'background': 'var(--background)',
        'surface-container': 'var(--surface-container)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.375rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-desktop': '2rem',
        'space-lg': '1.5rem',
        'gutter': '1rem',
        'margin': '1rem',
        'space-xs': '0.25rem',
        'gutter-desktop': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'title-sm': ['Inter', 'sans-serif'],
        'data-metric': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'code-plate': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
