import {
  DashboardMetrics,
  ParkingSpot,
  ParkingSession,
  Garage,
  PricingTier,
  ReportData,
} from '../types';

export const MOCK_GARAGES: Garage[] = [
  {
    id: 'gar_dt_01',
    name: 'Downtown Central Station',
    code: 'DOWNTOWN_L1_3',
    address: '401 Commerce St, Metro Core',
    levels: ['Level 1', 'Level 2', 'Level 3'],
    totalCapacity: 250,
    activeStatus: true,
    apiStatus: '200 OK',
    latencyMs: 38,
  },
  {
    id: 'gar_west_02',
    name: 'Westside Transit Hub',
    code: 'WESTSIDE_G1',
    address: '820 Grand Avenue',
    levels: ['Level 1', 'Level 2'],
    totalCapacity: 180,
    activeStatus: true,
    apiStatus: '200 OK',
    latencyMs: 42,
  },
  {
    id: 'gar_harbor_03',
    name: 'Harbor Gate Plaza',
    code: 'HARBOR_PLAZA',
    address: '12 Marina Blvd',
    levels: ['Level 1', 'Level 2', 'Level 3', 'Level 4'],
    totalCapacity: 320,
    activeStatus: true,
    apiStatus: '200 OK',
    latencyMs: 29,
  },
];

export const MOCK_SPOTS: ParkingSpot[] = [
  { id: 'spot_c01', spotNumber: 'C01', level: 'Level 1', sector: 'Sector A (North)', type: 'compact', status: 'available', hourlyRate: 8, hasEvCharger: false },
  { id: 'spot_c02', spotNumber: 'C02', level: 'Level 1', sector: 'Sector A (South)', type: 'compact', status: 'occupied', hourlyRate: 8, hasEvCharger: false, currentVehiclePlate: '7XYZ901', parkedDuration: '2h 15m' },
  { id: 'spot_s01', spotNumber: 'S01', level: 'Level 1', sector: 'Sector A', type: 'standard', status: 'occupied', hourlyRate: 10, hasEvCharger: false, currentVehiclePlate: '9BCA442', parkedDuration: '4h 00m' },
  { id: 'spot_s02', spotNumber: 'S02', level: 'Level 1', sector: 'Sector A', type: 'standard', status: 'available', hourlyRate: 10, hasEvCharger: false },
  { id: 'spot_e01', spotNumber: 'E01', level: 'Level 1', sector: 'Sector B (EV Zone)', type: 'ev', status: 'available', hourlyRate: 12, hasEvCharger: true, chargerPowerKw: 22 },
  { id: 'spot_e02', spotNumber: 'E02', level: 'Level 1', sector: 'Sector B (EV Zone)', type: 'ev', status: 'occupied', hourlyRate: 12, hasEvCharger: true, chargerPowerKw: 22, currentVehiclePlate: 'EV-3021', parkedDuration: '1h 12m' },
  { id: 'spot_b01', spotNumber: 'B01', level: 'Level 1', sector: 'Sector B', type: 'standard', status: 'occupied', hourlyRate: 10, hasEvCharger: false, currentVehiclePlate: '3MTA990', parkedDuration: '0h 42m' },
  { id: 'spot_b02', spotNumber: 'B02', level: 'Level 1', sector: 'Sector B', type: 'standard', status: 'occupied', hourlyRate: 10, hasEvCharger: false, currentVehiclePlate: '6PAX112', parkedDuration: '5h 19m' },
  
  // Level 2 Spots
  { id: 'spot_c108', spotNumber: 'C-108', level: 'Level 2', sector: 'Sector A', type: 'compact', status: 'available', hourlyRate: 8, hasEvCharger: false },
  { id: 'spot_e204', spotNumber: 'E-204', level: 'Level 2', sector: 'Sector B', type: 'ev', status: 'available', hourlyRate: 12, hasEvCharger: true, chargerPowerKw: 22 },
  { id: 'spot_s210', spotNumber: 'S-210', level: 'Level 2', sector: 'Sector C', type: 'standard', status: 'occupied', hourlyRate: 10, hasEvCharger: false, currentVehiclePlate: 'TEX-4491', parkedDuration: '1h 05m' },
  { id: 'spot_e208', spotNumber: 'E-208', level: 'Level 2', sector: 'Sector B', type: 'ev', status: 'occupied', hourlyRate: 12, hasEvCharger: true, chargerPowerKw: 22, currentVehiclePlate: '5ABT812', parkedDuration: '3h 40m' },
  { id: 'spot_s215', spotNumber: 'S-215', level: 'Level 2', sector: 'Sector C', type: 'standard', status: 'available', hourlyRate: 10, hasEvCharger: false },

  // Level 3 Spots
  { id: 'spot_s312', spotNumber: 'S-312', level: 'Level 3', sector: 'Sector C', type: 'standard', status: 'available', hourlyRate: 10, hasEvCharger: false },
  { id: 'spot_c302', spotNumber: 'C-302', level: 'Level 3', sector: 'Sector A', type: 'compact', status: 'occupied', hourlyRate: 8, hasEvCharger: false, currentVehiclePlate: 'WA-902-KL', parkedDuration: '6h 10m' },
  { id: 'spot_e305', spotNumber: 'E-305', level: 'Level 3', sector: 'Sector B', type: 'ev', status: 'available', hourlyRate: 12, hasEvCharger: true, chargerPowerKw: 11 },
];

export const MOCK_SESSIONS: ParkingSession[] = [
  {
    id: 'ses_101',
    licensePlate: '7XYZ901',
    vehicleType: 'compact',
    spotId: 'spot_c02',
    spotNumber: 'C02',
    level: 'Level 1',
    sector: 'Sector A',
    entryTime: new Date(Date.now() - 2.25 * 3600 * 1000).toISOString(),
    durationMinutes: 135,
    formattedDuration: '2h 15m',
    status: 'active',
  },
  {
    id: 'ses_102',
    licensePlate: '9BCA442',
    vehicleType: 'standard',
    spotId: 'spot_s01',
    spotNumber: 'S01',
    level: 'Level 1',
    sector: 'Sector A',
    entryTime: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    durationMinutes: 240,
    formattedDuration: '4h 00m',
    status: 'active',
  },
  {
    id: 'ses_103',
    licensePlate: 'EV-3021',
    vehicleType: 'ev',
    spotId: 'spot_e02',
    spotNumber: 'E02',
    level: 'Level 1',
    sector: 'Sector B',
    entryTime: new Date(Date.now() - 1.2 * 3600 * 1000).toISOString(),
    durationMinutes: 72,
    formattedDuration: '1h 12m',
    status: 'active',
  },
  {
    id: 'ses_104',
    licensePlate: '3MTA990',
    vehicleType: 'standard',
    spotId: 'spot_b01',
    spotNumber: 'B01',
    level: 'Level 1',
    sector: 'Sector B',
    entryTime: new Date(Date.now() - 0.7 * 3600 * 1000).toISOString(),
    durationMinutes: 42,
    formattedDuration: '0h 42m',
    status: 'active',
  },
  {
    id: 'ses_105',
    licensePlate: '6PAX112',
    vehicleType: 'standard',
    spotId: 'spot_b02',
    spotNumber: 'B02',
    level: 'Level 1',
    sector: 'Sector B',
    entryTime: new Date(Date.now() - 5.3 * 3600 * 1000).toISOString(),
    durationMinutes: 319,
    formattedDuration: '5h 19m',
    status: 'overstay',
  },
  {
    id: 'ses_106',
    licensePlate: 'TEX-4491',
    vehicleType: 'standard',
    spotId: 'spot_s210',
    spotNumber: 'S-210',
    level: 'Level 2',
    sector: 'Sector C',
    entryTime: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    exitTime: new Date().toISOString(),
    durationMinutes: 210,
    formattedDuration: '3h 30m',
    status: 'completed',
    paymentMethod: 'card',
    feeBreakdown: {
      firstHourRate: 10,
      additionalHourRate: 8,
      billedHours: 4,
      actualDurationMinutes: 210,
      subtotal: 34,
      taxAmount: 2.72,
      dailyMaxCap: 40,
      capStatus: 'Not Exceeded',
      totalFee: 36.72,
    },
  },
];

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  totalCapacity: 250,
  availableSpots: 68,
  occupiedSpots: 182,
  occupancyPercentage: 72.8,
  availableRatePerHour: 12,
  evPortsAvailable: 7,
  evPortsTotal: 24,
  evPortsCharging: 17,
  turnoverToday: 342,
  netRevenueToday: 4890.5,
  avgRevenuePerTicket: 14.3,
  revenueChangePercent: 8.4,
  floorOccupancy: [
    { level: 'Level 1', occupied: 78, total: 90, percentage: 86.6 },
    { level: 'Level 2', occupied: 64, total: 80, percentage: 80.0 },
    { level: 'Level 3', occupied: 40, total: 80, percentage: 50.0 },
  ],
  recentActivity: [
    { id: 'act_1', licensePlate: '7XYZ901', spotNumber: 'C01', level: 'L1', type: 'check_in', timestamp: '2 mins ago', status: 'Parked' },
    { id: 'act_2', licensePlate: 'EV-3021', spotNumber: 'E02', level: 'L1', type: 'check_in', timestamp: '14 mins ago', status: 'Parked' },
    { id: 'act_3', licensePlate: 'TEX-4491', spotNumber: 'S-210', level: 'L2', type: 'check_out', timestamp: '28 mins ago', status: 'Departed' },
    { id: 'act_4', licensePlate: '3MTA990', spotNumber: 'B01', level: 'L1', type: 'check_in', timestamp: '42 mins ago', status: 'Parked' },
    { id: 'act_5', licensePlate: 'WA-902-KL', spotNumber: 'C-302', level: 'L3', type: 'check_in', timestamp: '1 hour ago', status: 'Parked' },
  ],
};

export const MOCK_PRICING_TIERS: PricingTier[] = [
  { id: 'pr_compact', vehicleType: 'compact', name: 'Compact Sedan / Mini', firstHourRate: 8, additionalHourRate: 6, dailyMaxCap: 24, evFeePerHour: 0 },
  { id: 'pr_standard', vehicleType: 'standard', name: 'Standard SUV / Truck', firstHourRate: 10, additionalHourRate: 8, dailyMaxCap: 30, evFeePerHour: 0 },
  { id: 'pr_ev', vehicleType: 'ev', name: 'EV Fast Bay (Level 2 22kW)', firstHourRate: 12, additionalHourRate: 10, dailyMaxCap: 35, evFeePerHour: 4 },
];

export const MOCK_REPORT_DATA: ReportData = {
  revenueTrend: [
    { hour: '06:00', revenue: 240, occupancy: 25 },
    { hour: '08:00', revenue: 680, occupancy: 55 },
    { hour: '10:00', revenue: 1240, occupancy: 78 },
    { hour: '12:00', revenue: 1980, occupancy: 88 },
    { hour: '14:00', revenue: 2850, occupancy: 92 },
    { hour: '16:00', revenue: 3720, occupancy: 85 },
    { hour: '18:00', revenue: 4410, occupancy: 74 },
    { hour: '20:00', revenue: 4890, occupancy: 62 },
  ],
  typeDistribution: [
    { name: 'Standard', count: 110, value: 60.4 },
    { name: 'Compact', count: 52, value: 28.6 },
    { name: 'EV Charging', count: 20, value: 11.0 },
  ],
  occupancyByHour: [
    { hour: '08:00', compact: 20, standard: 45, ev: 10 },
    { hour: '11:00', compact: 35, standard: 85, ev: 18 },
    { hour: '14:00', compact: 45, standard: 105, ev: 22 },
    { hour: '17:00', compact: 40, standard: 90, ev: 19 },
    { hour: '20:00', compact: 25, standard: 60, ev: 12 },
  ],
  summary: {
    totalSessions: 342,
    totalRevenue: 4890.5,
    avgDurationMinutes: 168,
    peakOccupancyTime: '14:30 PM (94.2%)',
  },
};
